[package]
name = "petscan_rs"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
chrono = "*"
config = "*"
serde_json = "*"
url = "*"
rayon = "*"
htmlescape = "*"
rand = "*"
#mysql = { version="^17" }#, features = ["ssl"] }
mysql_async = "0.24.0-alpha"
reqwest = { version = "*", features = ["json"] }
time = "^0.2.9"
percent-encoding = "*"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" , branch = "tokio" }
async-trait = "0.1.30"
async-recursion = "0.3.1"

tokio = { version = "^0.2", features = ["macros","fs","sync"] }
tokio-util = "*"
hyper = "*"
#warp = "0.2.2"
qstring = "*"
futures = "*"

#[profile.release]
#lto = "fat"
#codegen-units = 1
#target-cpu = "native"
#panic = "abort"
