[package]
name = "petscan_rs"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
chrono = "*"
config = "*"
serde_json = "*"
url = "*"
rayon = "*"
htmlescape = "*"
rand = "*"
mysql = { version="^18" }#, features = ["ssl"] }
reqwest = { version = "^0.10", features = ["blocking", "json"] }
time = "^0.2.9"
percent-encoding = "*"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
#actix-web = { version = "3.0.0-alpha.1", default-features = true }
actix-web = "^2.0.0"
actix-files = "*"
actix-http = "*"
actix-rt = "^1"
qstring = "*"
futures = "*"

[profile.release]
lto = "fat"
codegen-units = 1
#target-cpu = "native"
panic = "abort"
